resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:
- name: pcf-automation
  type: pivnet
  source:
    api_token: {{pivnet_api_token}}
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    uri: {{automation_repo}}
#    private_key: {{git_private_key}}

- name: credentials
  type: git
  source:
    uri: {{automation_private_repo}}
    private_key: {{git_private_key}}

jobs:
- name: ((foundation))-((pivnet_product_slug))
  serial: true
  plan:
  - aggregate:
    - get: configuration
      trigger: false
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: credentials
      params:
        unpack: true

  - task: vars-interpolate
    image: pcf-automation-image
    file: configuration/fixes/tasks/vars-interpolate.yml
    input_mapping:
      config: configuration
      vars: credentials
    params:
      VARS_FILES: vars/((foundation))/common.yml
      CONFIG_FILE: config/templates/env.yml
    output_mapping:
      interpolated-files: configuration

  - task: download-product
    image: pcf-automation-image
    file: configuration/fixes/tasks/download-product.yml
    input_mapping:
      config: configuration
      secrets: credentials
    params:
      CONFIG_FILE: config/templates/pivnet.yml
      VARS_FILES: secrets/((foundation))/common.yml secrets/((foundation))/((pivnet_product_slug)).yml

  - task: upload-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upload-product.yml
    input_mapping:
      product: downloaded-product
      env: configuration
    params:
      ENV_FILE: config/templates/env.yml

  - task: stage-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: downloaded-product
      env: configuration
    params:
      ENV_FILE: config/templates/env.yml

  - task: upload-stemcell
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      env: configuration
      stemcell: downloaded-stemcell
    params:
      ENV_FILE: config/templates/env.yml

  - task: assign-stemcell
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/assign-stemcell.yml
    input_mapping:
      env: configuration
      config: assign-stemcell-config
    params:
      ENV_FILE: config/templates/env.yml

  - task: params-interpolate
    image: pcf-automation-image
    file: configuration/fixes/tasks/params-interpolate.yml
    input_mapping:
      config: tile-config
      vars: credentials
    params:
      VARS_FILES: vars/((foundation))/common.yml vars/((foundation))/((pivnet_product_slug)).yml
    output_mapping:
      interpolated-files: tile-config

  - task: configure-product
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: tile-config
      env: configuration
      vars: tile-config
      secrets: credentials
    params:
      CONFIG_FILE: ((config_file))
      VARS_FILES: ((vars_files)) secrets/((foundation))/common.yml secrets/((foundation))/((pivnet_product_slug)).yml
      ENV_FILE: config/templates/env.yml

- name: apply-changes
  serial: true
  plan:
  - aggregate:
    - get: configuration
      trigger: false
      passed: [ ((foundation))-((pivnet_product_slug)) ]
      params:
        unpack: true
    - get: pcf-automation-image
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: pcf-automation-tasks
      resource: pcf-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    - get: credentials
      params:
        unpack: true

  - task: vars-interpolate
    image: pcf-automation-image
    file: configuration/fixes/tasks/vars-interpolate.yml
    input_mapping:
      config: configuration
      vars: credentials
    params:
      VARS_FILES: vars/((foundation))/common.yml
      CONFIG_FILE: config/templates/env.yml
    output_mapping:
      interpolated-files: configuration

  - task: apply-product-changes
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/apply-changes.yml
    input_mapping:
      env: configuration
    params:
      ENV_FILE: config/templates/env.yml
